// socket types

module.exports = {
    VIDEO_START_PLAYING: "VIDEO_START_PLAYING",
    VIDEO_END_VIDEO: "VIDEO_END_VIDEO",
    
    POPUP_DESTROY: "POPUP_DESTROY",
    POPUP_PUSH: "POPUP_PUSH",
    POPUP_NOT_PUSHED: "POPUP_NOT_PUSHED"

}